### ISSUE TITLE
Error: The system cannot find the path specified (solution found)

### ISSUE THREAD

**Issue by hogash** [sindresorhus/sublime-autoprefixer#45]
Hey guys, such a great work you're doing and love it!!

I get this error when i'm using Ctrl+Alt+p (on Win8) + Sublime3
Error: The system cannot find the path specified (screenshot here http://screencast.com/t/mfTPeLEnPd )

Do you have any idea why this happenes? I have NodeJS installed, and checked version:
C:\Users\Marius>node -v
v0.10.31

Thank you so much!!

Marius

**Comment by alexilyaev** [comment]
Since the bump of `autoprefixer-core` to `4.0.0`, this issue is resolved.
The `"ie > 8"` syntax now works as expected.

**Comment by chyvak1831** [comment]
Hi @alexilyaev . Can you say how you fixed problem with ">"? I have this problem in sublime3, but I am not indestand what you do for fix this (this "Since the bump of autoprefixer-core to 4.0.0, this issue is resolved." - or this you may that autoprefixer updated and all working ok?)

Thanks!

p.s.: autoprefixer I am install a few days ago. I.e. it new version.

**Comment by tinktonk** [comment]
I have the same problem with sublime 3. Cant get the > to work with any browser. Shouldnt this work in the autoprefxer configuration?
"browsers": ["last 2 versions","ie => 8"]

**Comment by tinktonk** [comment]
its a lot of work to start listing all browsers that i need support for...

**Comment by alexilyaev** [comment]
@chyvak1831 @tinktonk The latest version of `sublime-autoprefixer` works ok for me.
Try re-installing the package in Sublime.
I also have `autoprefixer@5.1.0` installed using `npm`, not sure it's related.
But try running `autoprefixer` directly on your file.
